seed: 2002
lr: 0.0001
batch_size: 32
border_threshold: 30
epochs: 20
data_folder: Huron_data
experiment_name: test
criterion: dice
freeze_classifier: False
freeze_pixel_module: False
freeze_transformer_decoder: False
num_labels: 2
