seed: 2002
lr: 0.0001
batch_size: 8
epochs: 20
data_folder: Huron_data
experiment_name: test
criterion: dice
freeze_classifier: False
freeze_pixel_encoder: False
freeze_pixel_decoder: False
freeze_transformer_decoder: False
